using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;

namespace FontChanger.ShaderGen;

/// <summary>
/// Completes FontEdgePS.hlsl and compiles it: writes the generated functions in place of its marker line, compiles the
/// result as the plugin used to at run time (ps_5_0, main, optimization level 3), and writes the bytecode, the completed
/// source and its listing.
/// </summary>
/// <remarks>
/// Usage: FontChanger.ShaderGen &lt;FontEdgePS.hlsl&gt; &lt;output .cso&gt;. The completed source and listing go next to the
/// output (.hlsl, .asm). Compile errors go to stderr in the "file(line,col): error" form, and the exit code is 1.
/// </remarks>
internal static class Program
{
    private const string Marker = "// <generated by FontChanger.ShaderGen: SQUARE_REACH and DilateGatheredSquare>";

    private static int Main(string[] args)
    {
        if (args.Length != 2)
        {
            Console.Error.WriteLine("usage: FontChanger.ShaderGen <FontEdgePS.hlsl> <output .cso>");
            return 2;
        }

        var templatePath = Path.GetFullPath(args[0]);
        var outputPath = Path.GetFullPath(args[1]);
        var template = File.ReadAllText(templatePath).Replace("\r\n", "\n");
        var at = template.IndexOf(Marker, StringComparison.Ordinal);
        if (at < 0)
        {
            Console.Error.WriteLine($"{templatePath}: error: the marker line \"{Marker}\" is missing.");
            return 1;
        }

        var source = template[..at] + FontEdgeSquares.Generate() + template[(at + Marker.Length)..];
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        var sourcePath = Path.ChangeExtension(outputPath, ".hlsl");
        File.WriteAllText(sourcePath, source);

        // Errors name the completed source, whose lines match the template's up to the marker.
        if (!D3DCompiler.Compile(Encoding.UTF8.GetBytes(source), sourcePath, "main", "ps_5_0", out var code, out var messages))
        {
            Console.Error.WriteLine(messages);
            return 1;
        }

        if (messages.Length > 0)
            Console.WriteLine(messages);
        File.WriteAllBytes(outputPath, code);
        File.WriteAllText(Path.ChangeExtension(outputPath, ".asm"), D3DCompiler.Disassemble(code));
        return 0;
    }
}

/// <summary>
/// The generated part of FontEdgePS.hlsl: for a one-hot Channel and reaches 1 to <see cref="SquareReach"/>, a function
/// per reach that takes the whole square of samples from gathers, written out statement by statement (the channel is a
/// literal at each call). FXC compiles that several times faster than the same code as unrolled loops over arrays.
/// </summary>
internal static class FontEdgeSquares
{
    public const int SquareReach = 4;

    private const int ChannelCount = 4;

    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.Append($"#define SQUARE_REACH {SquareReach}\n\n");
        sb.Append($"// Reaches 1 to {SquareReach} for a one-hot Channel c (a literal), one function per reach: the (2R + 1)^2 samples\n");
        sb.Append("// around Uv from the (R + 1)^2 gathers at the texel corners around them, every texel gathered once.\n");
        for (var r = 1; r <= SquareReach; r++)
            sb.Append(Square(r)).Append('\n');

        sb.Append($"// Channel c (0 to 3), reach r (1 to {SquareReach}).\n");
        sb.Append("float DilateGatheredSquare(PSInput input, int c, int r, float2 texel, float2 size, float rim)\n{\n");
        sb.Append("    [branch]\n    switch (c * 8 + r)\n    {\n");
        for (var c = 0; c < ChannelCount; c++)
        {
            for (var r = 1; r <= SquareReach; r++)
                sb.Append($"    case {(c * 8) + r}:\n        return DilateGathered{r}(input, {c}, texel, size, rim);\n");
        }

        sb.Append("    default:\n        return 0;\n    }\n}");
        return sb.ToString();
    }

    /// <summary>
    /// Reach r for channel c (a literal): the (2r + 1)^2 samples around Uv from the (r + 1)^2 gathers at the texel corners
    /// around them. Gather (a, b) holds texel columns a, a + 1 of rows b, b + 1 (relative to the corner of Uv's
    /// footprint); sample row y blends texel rows y and y + 1 into columns, and sample x blends columns x and x + 1.
    /// </summary>
    private static string Square(int r)
    {
        var sb = new StringBuilder();
        void Emit(string line) => sb.Append(line).Append('\n');

        Emit($"float DilateGathered{r}(PSInput input, int c, float2 texel, float2 size, float rim)");
        Emit("{");
        Emit("    float2 corner, f;");
        Emit("    Footprint(input, texel, size, corner, f);");

        // The rectangle test of each column and row of samples.
        for (var i = -r; i <= r; i++)
        {
            var n = i + r;
            Emit($"    float u{n} = {Offset("input.Uv.x", i, "texel.x")}, v{n} = {Offset("input.Uv.y", i, "texel.y")};");
            Emit($"    bool column{n} = u{n} >= input.RectMin.x && u{n} <= input.RectMax.x;");
            Emit($"    bool row{n} = v{n} >= input.RectMin.y && v{n} <= input.RectMax.y;");
        }

        for (var b = -r; b <= r; b += 2)
        {
            for (var a = -r; a <= r; a += 2)
                Emit($"    float4 g{b + r}_{a + r} = Gather(c, corner, int2({a}, {b}));");
        }

        string Texel(int row, int col)
        {
            var b = row - ((row + r) % 2);
            var a = col - ((col + r) % 2);
            var component = row == b ? (col == a ? 'w' : 'z') : (col == a ? 'x' : 'y');
            return $"g{b + r}_{a + r}.{component}";
        }

        // Offsets r + 1 or further away weigh 0 (r is the furthest weighing more), those nearer than r - 1 exactly 1
        // (rim > r); the rest weigh rim - their distance.
        var weights = new HashSet<int>();
        Emit("    float alpha = 0;");
        for (var y = -r; y <= r; y++)
        {
            for (var col = -r; col <= r + 1; col++)
                Emit($"    float k{y + r}_{col + r} = lerp({Texel(y, col)}, {Texel(y + 1, col)}, f.y);");
            for (var x = -r; x <= r; x++)
            {
                var d2 = (x * x) + (y * y);
                if (d2 >= (r + 1) * (r + 1))
                    continue;
                var sample = $"lerp(k{y + r}_{x + r}, k{y + r}_{x + r + 1}, f.x)";
                if (d2 >= (r - 1) * (r - 1))
                {
                    if (weights.Add(d2))
                        Emit($"    float w{d2} = saturate(rim - {Math.Sqrt(d2).ToString("F9", CultureInfo.InvariantCulture)});");
                    sample += $" * w{d2}";
                }

                Emit($"    if (row{y + r} && column{x + r})");
                Emit($"        alpha = max(alpha, {sample});");
            }
        }

        Emit("    return alpha;");
        Emit("}");
        return sb.ToString();
    }

    /// <summary>base + i * step, as written by hand.</summary>
    private static string Offset(string @base, int i, string step)
    {
        if (i == 0)
            return @base;
        var times = Math.Abs(i) == 1 ? step : $"{Math.Abs(i)} * {step}";
        return $"{@base} {(i > 0 ? '+' : '-')} {times}";
    }
}

/// <summary>D3DCompile and D3DDisassemble from d3dcompiler_47.dll.</summary>
internal static unsafe partial class D3DCompiler
{
    private const uint OptimizationLevel3 = 1 << 15;

    public static bool Compile(byte[] source, string name, string entry, string target, out byte[] code, out string messages)
    {
        void* codeBlob = null;
        void* errorBlob = null;
        try
        {
            var hr = D3DCompile(source, (nuint)source.Length, name, 0, 0, entry, target, OptimizationLevel3, 0, &codeBlob, &errorBlob);
            messages = errorBlob is null ? string.Empty : Encoding.UTF8.GetString(BlobBytes(errorBlob)).TrimEnd('\0', '\r', '\n');
            code = hr >= 0 && codeBlob is not null ? BlobBytes(codeBlob) : [];
            return hr >= 0;
        }
        finally
        {
            Release(codeBlob);
            Release(errorBlob);
        }
    }

    public static string Disassemble(byte[] code)
    {
        void* blob = null;
        try
        {
            Marshal.ThrowExceptionForHR(D3DDisassemble(code, (nuint)code.Length, 0, null, &blob));
            return Encoding.UTF8.GetString(BlobBytes(blob)).TrimEnd('\0');
        }
        finally
        {
            Release(blob);
        }
    }

    // ID3DBlob: IUnknown (QueryInterface, AddRef, Release), GetBufferPointer, GetBufferSize.
    private static byte[] BlobBytes(void* blob)
    {
        var vtable = *(void***)blob;
        var pointer = ((delegate* unmanaged[Stdcall]<void*, void*>)vtable[3])(blob);
        var size = ((delegate* unmanaged[Stdcall]<void*, nuint>)vtable[4])(blob);
        return new ReadOnlySpan<byte>(pointer, checked((int)size)).ToArray();
    }

    private static void Release(void* unknown)
    {
        if (unknown is not null)
            ((delegate* unmanaged[Stdcall]<void*, uint>)(*(void***)unknown)[2])(unknown);
    }

    [LibraryImport("d3dcompiler_47.dll", StringMarshalling = StringMarshalling.Utf8)]
    private static partial int D3DCompile(
        byte[] srcData, nuint srcDataSize, string sourceName, nint defines, nint include, string entrypoint, string target,
        uint flags1, uint flags2, void** code, void** errorMsgs);

    [LibraryImport("d3dcompiler_47.dll", StringMarshalling = StringMarshalling.Utf8)]
    private static partial int D3DDisassemble(byte[] srcData, nuint srcDataSize, uint flags, string? comments, void** disassembly);
}
